<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Barbatos.Migration.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Barbatos.Migration.Core\Barbatos.Migration.Core.csproj" />
    <ProjectReference Include="..\..\src\Barbatos.Migration.Csv\Barbatos.Migration.Csv.csproj" />
    <ProjectReference Include="..\..\src\Barbatos.Migration.Database\Barbatos.Migration.Database.csproj" />
    <ProjectReference Include="..\..\src\Barbatos.Migration.FileSystem\Barbatos.Migration.FileSystem.csproj" />
    <ProjectReference Include="..\..\src\Barbatos.Migration.Ini\Barbatos.Migration.Ini.csproj" />
    <ProjectReference Include="..\..\src\Barbatos.Migration.Json\Barbatos.Migration.Json.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
